# -*- coding: utf-8 -*-
{
    'name': 'library management',
    'version': '18.0.1.8.0',
    'author' : 'Pratham shah',
    'summary': 'Library management module',
    'description': """
        Module that is designed to manage all the functions of a library 
        """,
    'category': 'Library_management/Library_management',
    'website': 'https://www.aktivsoftware.com',
    'depends': [
        'base','stock', 'web', 'sale_management','website_sale','product','purchase','base_automation','hr','mail','account','website','point_of_sale',
    ],
    'data': [
        'security/res_groups.xml',
        'security/ir.model.access.csv',
        'reports/library_location_report_action.xml',
        'reports/library_location_report.xml',
        'reports/report_invoice_inherit.xml',
        'views/library_book.xml',
        'views/library_member.xml',
        'views/library_book_tag.xml',
        'views/library_book_category.xml',
        'views/library_book_location.xml',
        'views/product_template_view.xml',
        'views/product_variant_menu.xml',
        'views/res_user.xml',
        'views/sale_order.xml',
        'views/borrow_transaction_history.xml',
        'views/res_partner.xml',
        'views/main.xml',
        'views/contact_form.xml',
        'views/stock_warehouse.xml',
        'views/res_config_setting.xml',
        'views/customer_page.xml',
        'views/website_product_template.xml',
        'views/product_template.xml',
        'views/product_variant_easy_edit_view_vendor_inherit.xml',
        'views/add_to_cart.xml',
        'views/website_menu.xml',
        'wizard/bulk_book.xml',
        'wizard/sale_order_wizard.xml',
        'wizard/borrow_books_warning_wizard.xml',
        'data/ir_sequence.xml',
        'data/ir_cron.xml',
        'data/mail_template_data.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            # 'ak_library_management/static/src/scss/contactus.scss',
            'ak_library_management/static/src/js/customer_fetch.js',
        ],
        'web.assets_backend': [

        ],
        'point_of_sale._assets_pos': [
            # 'ak_library_management/static/src/js/custom_pos.js',
            # 'ak_library_management/static/src/scss/custom_pos_styles.scss',
            'ak_library_management/static/src/xml/pos_product_template.xml',
            'ak_library_management/static/src/xml/pos_product_productscreen.xml',
        ],
    },
    'installable': True,
    'license': 'LGPL-3',
}
